### ISSUE TITLE
Enable org-specific tagged controllers

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk-k8s#10]
In a multi-tenant system, there may be more than one controller. The controller should only react to ingresses that have the correct namespace or ID associated as an annotation.

**Comment by drpebcak** [comment]
Was this actually done, or has it just been closed due to inactivity?

**Comment by excieve** [comment]
@drpebcak This issue is a little ambiguous — the title doesn't appear to match the description. The description though should be solved by #27, which is done.
