### ISSUE TITLE
Updates to other rules than the first one are not applied

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk-k8s#37]
Function which checks whether there are any ingress spec changes only inspects the first item in the rules list:
https://github.com/TykTechnologies/tyk-k8s/blob/1193b04e62692a9cccb5ec64a610c1aaf28f29a2/ingress/ingress.go#L341

**Comment by joshblakeley** [comment]
We actually ignore all rules than the first one altogether at the moment when templating the APIDefs.

So currently we create an API per path defined but they will both share the same custom domain. There needs to be a feature enhancement ticket to add support for templating apis per domain and then per path as the multiple rules are iterated through.

**Comment by excieve** [comment]
@joshblakeley `doAdd` ranges over the rules and inspects paths of each rule:
https://github.com/TykTechnologies/tyk-k8s/blob/1193b04e62692a9cccb5ec64a610c1aaf28f29a2/ingress/ingress.go#L215

**Comment by joshblakeley** [comment]
Ahhh great. Don't know why I thought otherwise!

**Comment by joshblakeley** [comment]
fixed by #40
